### ISSUE TITLE
bower is out of date in the snapstore

### ISSUE THREAD

**Issue by xnox** [bower/bower#2538]
bower in the snapstore is 1.8.0, please upgrade to 1.8.8 and ideally build the snap direct out of github. (possibly you need to take ownership of the snap too, to achieve that).

Currently that's the status for bower:

```
$ snap info bower
name:      bower
summary:   A package manager for the web
publisher: Joe Borg (joeborg)
contact:   https://github.com/bower/bower/issues
license:   Other Open Source
description: |
  Web sites are made of lots of things — frameworks, libraries, assets, and utilities.
  Bower manages all these things for you.
snap-id: sqteCX7tnM1bxCX34c6Mt9DxxQJkpMS9
channels:
  stable:    1.8.0 2017-05-17 (2) 13MB classic
  candidate: ↑                         
  beta:      ↑                         
  edge:      ↑ 
```

**Comment by xnox** [comment]
oh well, and it crashes in the snapstore upon execution, possibly that snap needs to be removed.

It would be great if I could install an uptodate bower from the snapstore

**Comment by sheerun** [comment]
I've filed for transfer of this snap to me

**Comment by sheerun** [comment]
I have ownership of it but I'm unable to create snap where both bower and git works. I'm using following one: 

```yaml
name: bower
version: 1.8.8
summary: A package manager for the web
description: Bower offers a generic, unopinionated solution to the problem of front-end package management
confinement: devmode
grade: stable
parts:
  bower:
    node-packages:
      - bower@1.8.8
    stage-packages:
      - openssl
      - curl
      - git
    plugin: nodejs
    source: .
apps:
  bower:
    command: bin/bower
```

```bash
snap remove bower
snapcraft clean bower
snapcraft prime
snap try prime
```

I get error:

```
bower info jquery
bower not-cached    https://github.com/jquery/jquery-dist.git#*
bower resolve       https://github.com/jquery/jquery-dist.git#*
bower ECMDERR       Failed to execute "git ls-remote --tags --heads https://github.com/jquery/jquery-dist.git", exit code of #128 fatal: Unable to find remote helper for 'https'
```

I'd appreciate help to setup this otherwise it can take some time for me to figure it out..
