### ISSUE TITLE
Bower home page section anchor links incorrectly visible on narrow resolutions

### ISSUE THREAD

**Issue by lokesh** [bower/bower#871]
![anchor links visible](https://f.cloud.github.com/assets/51469/1143783/5daddb82-1d58-11e3-8ad8-23294ab1d478.png)

The css rule that hides the anchors is inside of a desktop targeting media query, app.css:247:

``` css
  h1 > a,
  h2 > a,
  h3 > a {
    display:none;
  }
```
